# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.IntegerField(unique=True)),
                ('foto', models.ImageField(upload_to=b'')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
