# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20160303_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion_1',
            field=models.TextField(max_length=255),
        ),
    ]
