# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='direccion_1',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='telefono',
        ),
    ]
